export const CQA_CONFIG = {
    id: 7,
    audioFiles: [],
    voipTrunkId: '10004-1726243876',
    aiEnabled: true,
    clientId: 1726243876,
    createdAt: '2024-11-07T12:46:53.252Z',
    updatedAt: '2024-11-08T08:58:52.513Z',
};

export const CQA_STAT = {
    data: [
        {
            rating: '10',
            callResult: 'successful',
            clientNumber: '+79101234567',
            managerData: 'Виталий Пупкин',
            managerNumber: '460',
            country: 'Россия',
            region: 'Москва',
            city: 'Москва',
            date: '2024-11-07',
        },
        {
            rating: '3',
            callResult: 'successful',
            clientNumber: '+79031234566',
            managerData: 'Виталий Пупкин',
            managerNumber: '460',
            country: 'Россия',
            region: 'Челябинская обл',
            city: 'Челябинск',
            date: '2024-11-07',
        },
        {
            rating: '5',
            callResult: 'successful',
            clientNumber: '+74991136033',
            managerData: 'Иванов Иван',
            managerNumber: '102',
            country: 'Россия',
            region: 'Московская обл',
            city: 'Раменское',
            date: '2024-11-07',
        },
        {
            rating: '0',
            callResult: 'unknown',
            clientNumber: '+73211236549',
            managerData: 'Мария',
            managerNumber: '321',
            country: 'Россия',
            region: 'Москва',
            city: 'Москва',
            date: '2024-11-07',
        },
    ],
    totalRecords: 4,
};
